[package]
name = "erabasic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
insta = "1.36.1"
pest = "2.7"
pest_derive = "2.7"
